---
sidebar: sidebar 
permalink: reference_limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, volume view, govcloud, cloud manager, Cloud Volumes ONTAP 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni. 
---
= Limitazioni note
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni.



== Cloud Manager non supporta i volumi FlexGroup

Anche se Cloud Volumes ONTAP supporta FlexGroup Volumes, non lo fa. Se si crea un volume FlexGroup da Gestore di sistema o dall'interfaccia CLI, impostare la modalità di gestione della capacità di Cloud Manager su Manuale. La modalità automatica potrebbe non funzionare correttamente con i volumi FlexGroup.



== Active Directory non è supportato per impostazione predefinita con le nuove installazioni di Cloud Manager

A partire dalla versione 3.4, le nuove installazioni di Cloud Manager non supportano l'utilizzo dell'autenticazione Active Directory dell'organizzazione per la gestione degli utenti. Se necessario, NetApp può aiutarti a configurare Active Directory con Cloud Manager. Fare clic sull'icona della chat in basso a destra in Cloud Manager per ottenere assistenza.



== Limitazioni dell'area geografica AWS GovCloud (USA)

* Cloud Manager deve essere implementato nell'area geografica AWS GovCloud (USA) se si desidera avviare istanze di Cloud Volumes ONTAP nell'area geografica AWS GovCloud (USA).
* Se implementato nell'area geografica AWS GovCloud (USA), Cloud Manager non è in grado di rilevare i cluster ONTAP in una configurazione NetApp Private Storage per Microsoft Azure o NetApp Private Storage per SoftLayer.




== Limitazioni di Volume View

* La vista volume non è supportata nell'area AWS GovCloud (USA), nell'ambiente AWS Commercial Cloud Services e in Microsoft Azure.
* La vista volume consente di creare solo volumi NFS.
* Cloud Manager non avvia le istanze di Cloud Volumes ONTAP BYOL nella vista volume.




== Cloud Manager non imposta i volumi iSCSI

Quando si crea un volume in Cloud Manager utilizzando Storage System View, è possibile scegliere il protocollo NFS o CIFS. Per creare un volume per iSCSI, è necessario utilizzare Gestore di sistema di OnCommand.



== Limitazione di Storage Virtual Machine (SVM)

Cloud Volumes ONTAP supporta una SVM per la gestione dei dati e una o più SVM utilizzate per il disaster recovery.

Cloud Manager non fornisce alcun supporto di configurazione o orchestrazione per il disaster recovery SVM. Inoltre, non supporta attività correlate allo storage su SVM aggiuntive. Per il disaster recovery di SVM, è necessario utilizzare System Manager o CLI.
