---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux,  svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk 
summary: 'I dettagli sulla configurazione predefinita di Cloud Manager e Cloud Volumes ONTAP possono aiutare l"amministratore dei sistemi.' 
---
= Configurazioni predefinite
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I dettagli sulla configurazione predefinita di Cloud Manager e Cloud Volumes ONTAP possono aiutare l'amministratore dei sistemi.



== Configurazione predefinita per Cloud Manager su Linux

Se hai bisogno di risolvere i problemi di Cloud Manager o del tuo host Linux, potrebbe aiutarti a capire come è configurato Cloud Manager.

* Se hai implementato Cloud Manager da NetApp Cloud Central (o direttamente da AWS Marketplace o Azure Marketplace), tieni presente quanto segue:
+
** In AWS, il nome utente per l'istanza EC2 Linux è ec2-user.
** Per AWS e Azure, il sistema operativo per l'immagine Cloud Manager è Red Hat Enterprise Linux 7.4 (HVM).
+
Il sistema operativo non include una GUI. Per accedere al sistema, è necessario utilizzare un terminale.



* La cartella di installazione di Cloud Manager si trova nella seguente posizione:
+
/opt/application/netapp/cloudmanager

* I file di log sono contenuti nella seguente cartella:
+
/opt/application/netapp/cloudmanager/log

* Il servizio Cloud Manager è denominato occm.
* Il servizio occm dipende dal servizio MySQL.
+
Se il servizio MySQL non è attivo, anche il servizio occm è inattivo.

* Cloud Manager installa i seguenti pacchetti sull'host Linux, se non sono già installati:
+
** 7zip
** AWSCLI
** Java
** Kubectl
** MySQL
** Tridentctl
** Wget






== Configurazione predefinita per Cloud Volumes ONTAP

La configurazione predefinita di Cloud Volumes ONTAP consente di configurare e amministrare i sistemi, in particolare se si conosce ONTAP perché la configurazione predefinita di Cloud Volumes ONTAP è diversa da ONTAP.

* Cloud Volumes ONTAP è disponibile come sistema a nodo singolo e come coppia ha in AWS e Azure.
* Cloud Manager crea una SVM per il servizio dei dati quando implementa Cloud Volumes ONTAP. Anche se è possibile creare un'altra SVM per la gestione dei dati da System Manager o CLI, l'utilizzo di più SVM per la gestione dei dati non è supportato.
* Per impostazione predefinita, vengono create diverse interfacce di rete:
+
** Una LIF di gestione del cluster
** Un LIF intercluster
** Una LIF di gestione dei nodi
** Una LIF di dati iSCSI
** Una LIF di dati CIFS e NFS
+

NOTE: Il failover LIF è disattivato per impostazione predefinita per Cloud Volumes ONTAP a causa dei requisiti EC2. La migrazione di una LIF a una porta diversa interrompe la mappatura esterna tra gli indirizzi IP e le interfacce di rete sull'istanza, rendendo la LIF inaccessibile.



* Cloud Volumes ONTAP invia i backup della configurazione a Cloud Manager utilizzando HTTPS.
* Una volta effettuato l'accesso a Cloud Manager, i backup sono accessibili da https://[]
* Cloud Manager imposta alcuni attributi di volume in modo diverso rispetto ad altri strumenti di gestione (ad esempio, System Manager o CLI).
+
La tabella seguente elenca gli attributi del volume impostati da Cloud Manager in modo diverso dai valori predefiniti:

+
[cols="15,85"]
|===
| Attributo | Valore stabilito da Cloud Manager 


| Modalità di dimensionamento automatico | crescere 


| Dimensionamento automatico massimo  a| 
1,000%


NOTE: L'amministratore di Cloud Manager può modificare questo valore dalla pagina Impostazioni.



| Stile di sicurezza | NTFS per CIFS Volumes UNIX per NFS Volumes 


| Stile garanzia di spazio | nessuno 


| Autorizzazioni UNIX (solo NFS) | 777 
|===
+
Per informazioni su questi attributi, consulta la pagina man _volume create_.





== Dati di boot e root per Cloud Volumes ONTAP

Oltre allo storage per i dati degli utenti, Cloud Manager acquista anche lo storage cloud per i dati di boot e root su ogni sistema Cloud Volumes ONTAP.



=== AWS

* Un disco SSD IOPS con provisioning per i dati di avvio Cloud Volumes ONTAP, che è di circa 45 GB e 1,250 PIOPS
* Un disco SSD General Purpose per i dati root Cloud Volumes ONTAP, che è di circa 140 GB
* Un'istantanea EBS per ogni disco di boot e disco root


In una coppia ha, entrambi i nodi Cloud Volumes ONTAP replicano il proprio disco root nel nodo partner.



=== Azure

* Un disco SSD Premium Storage per i dati di avvio Cloud Volumes ONTAP, pari a circa 73 GB
* Un disco SSD Premium Storage per i dati root Cloud Volumes ONTAP, pari a circa 140 GB
* Uno snapshot Azure per ogni disco di boot e disco root




=== Dove risiedono i dischi

Cloud Manager definisce lo storage di AWS e Azure come segue:

* I dati di avvio risiedono su un disco collegato all'istanza EC2 o alla macchina virtuale Azure.
+
Questo disco, che contiene l'immagine di avvio, non è disponibile per Cloud Volumes ONTAP.

* I dati root, che contengono la configurazione del sistema e i log, risiedono in aggr0.
* Il volume root della macchina virtuale di storage (SVM) risiede in aggr1.
* I volumi di dati risiedono anche in aggr1.

